- name: Git pull maven compile tomcat deploy
  hosts: webservers
  become: yes
  become_method: sudo
  vars:
     remote_warfile: /root/workspace/myproject/target/myproject.war
     remote_webapps: /usr/share/tomcat/webapps/
     local_git_credential: gitcredential/.git-credentials
     remote_git_credential: ~/.git-credentials

  tasks:
    - name: check out the repository on the host
      git: repo=https://github.com/anshumanbiswal26121981/sl_jenkins_assessment.git dest=/root/workspace/myproject/ accept_hostkey=yes

    - name: maven clean package
      command: mvn -f /root/workspace/myproject/pom.xml -X clean package